pipeline{
    agent any
    stages{
        stage('Setting'){
            steps{

                sh 'mv -f "/root/.jenkins/workspace/sushijie/framework/main.py" "/data/main.py"'
                sh 'cd "/data";python3 "main.py"'
                sh 'cd "/data/yaml";sh "ssh.sh"'
           }
        }
        stage('Build'){
           steps{

            sh 'cd "/data";python3 "main.py" waiting'
           }
        }
        stage('test'){
            steps{
                sh 'cd "/data";python3 "main.py" test'

            }
        }
    }
}
